- name: Ensure pip3 is installed
  yum:
    name: python3-pip
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

- name: create database
  community.mysql.mysql_db:
    login_host: "fnc-database.clcmaymew814.us-east-1.rds.amazonaws.com"
    login_user: "francis"
    login_password: "devopspbl"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "fnc-database.clcmaymew814.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "francis" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "devopspbl" }


